### ISSUE TITLE
error selecting 2chaptca or manually

### ISSUE THREAD

**Issue by mrongoz** [KevinLage/Edu-Account-creator#44]
Bro I found an error when I chose 2chaptca or manually

Traceback (most recent call last):
  File "Edu Bot.py", line 2335, in <module>
    use_captcha = input("1. 2Captcha \n2. Manually\n")
  File "<string>", line 1
    2Captcha
           ^
SyntaxError: unexpected EOF while parsing

**Comment by Saurabh-gitbase** [comment]
For selecting captcha type "1" 
for selecting Manually type "2"

**Comment by khp11** [comment]
this eror 
traceback (most recent call last):
  File "Edu Bot.py", line 2397, in <module>
    createaccount(collage, use_captcha)
  File "Edu Bot.py", line 109, in createaccount
    open("log.txt", "a+").write(str(E)+"\n")
IOError: [Errno 13] Permission denied: 'log.txt'
